import Header from "../_components/header"
import NavMenu from "../_components/nav-menu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>
        <Header menu={true} links={[
            { name: "Adicionar Alimento", link: "/kitchen/#adicionarcomida" },
            { name: "Tela TV", link: "/kitchen/telagrande" },
            { name: "Desperdício", link: "/kitchen/rest" },
            ]}/>
      </header>
        {children}
      </body>
    </html>
  )
}
