import type { Metadata } from "next";
import NavMenu from "../_components/nav-menu";

const listMenus: [string[], string[]] = [
  ["Café da Manhã", "Almoço", "Café da Tarde"],
  ["student/cafe-manha", "student/almoco", "student/cafe-tarde"]
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <NavMenu menus={listMenus} />
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
